//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tContinent", Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tContinent : object
    {
        
        private string sCodeField;
        
        private string sNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sCode
        {
            get
            {
                return this.sCodeField;
            }
            set
            {
                this.sCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tCurrency", Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tCurrency : object
    {
        
        private string sISOCodeField;
        
        private string sNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sISOCode
        {
            get
            {
                return this.sISOCodeField;
            }
            set
            {
                this.sISOCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tCountryCodeAndName", Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tCountryCodeAndName : object
    {
        
        private string sISOCodeField;
        
        private string sNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sISOCode
        {
            get
            {
                return this.sISOCodeField;
            }
            set
            {
                this.sISOCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tCountryCodeAndNameGroupedByContinent", Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tCountryCodeAndNameGroupedByContinent : object
    {
        
        private ServiceReference1.tContinent ContinentField;
        
        private ServiceReference1.tCountryCodeAndName[] CountryCodeAndNamesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public ServiceReference1.tContinent Continent
        {
            get
            {
                return this.ContinentField;
            }
            set
            {
                this.ContinentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public ServiceReference1.tCountryCodeAndName[] CountryCodeAndNames
        {
            get
            {
                return this.CountryCodeAndNamesField;
            }
            set
            {
                this.CountryCodeAndNamesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tCountryInfo", Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tCountryInfo : object
    {
        
        private string sISOCodeField;
        
        private string sNameField;
        
        private string sCapitalCityField;
        
        private string sPhoneCodeField;
        
        private string sContinentCodeField;
        
        private string sCurrencyISOCodeField;
        
        private string sCountryFlagField;
        
        private ServiceReference1.tLanguage[] LanguagesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sISOCode
        {
            get
            {
                return this.sISOCodeField;
            }
            set
            {
                this.sISOCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string sCapitalCity
        {
            get
            {
                return this.sCapitalCityField;
            }
            set
            {
                this.sCapitalCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string sPhoneCode
        {
            get
            {
                return this.sPhoneCodeField;
            }
            set
            {
                this.sPhoneCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string sContinentCode
        {
            get
            {
                return this.sContinentCodeField;
            }
            set
            {
                this.sContinentCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string sCurrencyISOCode
        {
            get
            {
                return this.sCurrencyISOCodeField;
            }
            set
            {
                this.sCurrencyISOCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public string sCountryFlag
        {
            get
            {
                return this.sCountryFlagField;
            }
            set
            {
                this.sCountryFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public ServiceReference1.tLanguage[] Languages
        {
            get
            {
                return this.LanguagesField;
            }
            set
            {
                this.LanguagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tLanguage", Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class tLanguage : object
    {
        
        private string sISOCodeField;
        
        private string sNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sISOCode
        {
            get
            {
                return this.sISOCodeField;
            }
            set
            {
                this.sISOCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo", ConfigurationName="ServiceReference1.CountryInfoServiceSoapType")]
    public interface CountryInfoServiceSoapType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ServiceReference1.ListOfContinentsByNameResponse ListOfContinentsByName(ServiceReference1.ListOfContinentsByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ListOfContinentsByNameResponse> ListOfContinentsByNameAsync(ServiceReference1.ListOfContinentsByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ServiceReference1.ListOfContinentsByCodeResponse ListOfContinentsByCode(ServiceReference1.ListOfContinentsByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ListOfContinentsByCodeResponse> ListOfContinentsByCodeAsync(ServiceReference1.ListOfContinentsByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ServiceReference1.ListOfCurrenciesByNameResponse ListOfCurrenciesByName(ServiceReference1.ListOfCurrenciesByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ListOfCurrenciesByNameResponse> ListOfCurrenciesByNameAsync(ServiceReference1.ListOfCurrenciesByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ServiceReference1.ListOfCurrenciesByCodeResponse ListOfCurrenciesByCode(ServiceReference1.ListOfCurrenciesByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ListOfCurrenciesByCodeResponse> ListOfCurrenciesByCodeAsync(ServiceReference1.ListOfCurrenciesByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ServiceReference1.CurrencyNameResponse CurrencyName(ServiceReference1.CurrencyNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CurrencyNameResponse> CurrencyNameAsync(ServiceReference1.CurrencyNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ServiceReference1.ListOfCountryNamesByCodeResponse ListOfCountryNamesByCode(ServiceReference1.ListOfCountryNamesByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ListOfCountryNamesByCodeResponse> ListOfCountryNamesByCodeAsync(ServiceReference1.ListOfCountryNamesByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ServiceReference1.ListOfCountryNamesByNameResponse ListOfCountryNamesByName(ServiceReference1.ListOfCountryNamesByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ListOfCountryNamesByNameResponse> ListOfCountryNamesByNameAsync(ServiceReference1.ListOfCountryNamesByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ServiceReference1.ListOfCountryNamesGroupedByContinentResponse ListOfCountryNamesGroupedByContinent(ServiceReference1.ListOfCountryNamesGroupedByContinentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ListOfCountryNamesGroupedByContinentResponse> ListOfCountryNamesGroupedByContinentAsync(ServiceReference1.ListOfCountryNamesGroupedByContinentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ServiceReference1.CountryNameResponse CountryName(ServiceReference1.CountryNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CountryNameResponse> CountryNameAsync(ServiceReference1.CountryNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ServiceReference1.CountryISOCodeResponse CountryISOCode(ServiceReference1.CountryISOCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CountryISOCodeResponse> CountryISOCodeAsync(ServiceReference1.CountryISOCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ServiceReference1.CapitalCityResponse CapitalCity(ServiceReference1.CapitalCityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CapitalCityResponse> CapitalCityAsync(ServiceReference1.CapitalCityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ServiceReference1.CountryCurrencyResponse CountryCurrency(ServiceReference1.CountryCurrencyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CountryCurrencyResponse> CountryCurrencyAsync(ServiceReference1.CountryCurrencyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ServiceReference1.CountryFlagResponse CountryFlag(ServiceReference1.CountryFlagRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CountryFlagResponse> CountryFlagAsync(ServiceReference1.CountryFlagRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ServiceReference1.CountryIntPhoneCodeResponse CountryIntPhoneCode(ServiceReference1.CountryIntPhoneCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CountryIntPhoneCodeResponse> CountryIntPhoneCodeAsync(ServiceReference1.CountryIntPhoneCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ServiceReference1.FullCountryInfoResponse FullCountryInfo(ServiceReference1.FullCountryInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.FullCountryInfoResponse> FullCountryInfoAsync(ServiceReference1.FullCountryInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ServiceReference1.FullCountryInfoAllCountriesResponse FullCountryInfoAllCountries(ServiceReference1.FullCountryInfoAllCountriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.FullCountryInfoAllCountriesResponse> FullCountryInfoAllCountriesAsync(ServiceReference1.FullCountryInfoAllCountriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ServiceReference1.CountriesUsingCurrencyResponse CountriesUsingCurrency(ServiceReference1.CountriesUsingCurrencyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.CountriesUsingCurrencyResponse> CountriesUsingCurrencyAsync(ServiceReference1.CountriesUsingCurrencyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ServiceReference1.ListOfLanguagesByNameResponse ListOfLanguagesByName(ServiceReference1.ListOfLanguagesByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ListOfLanguagesByNameResponse> ListOfLanguagesByNameAsync(ServiceReference1.ListOfLanguagesByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ServiceReference1.ListOfLanguagesByCodeResponse ListOfLanguagesByCode(ServiceReference1.ListOfLanguagesByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ListOfLanguagesByCodeResponse> ListOfLanguagesByCodeAsync(ServiceReference1.ListOfLanguagesByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ServiceReference1.LanguageNameResponse LanguageName(ServiceReference1.LanguageNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.LanguageNameResponse> LanguageNameAsync(ServiceReference1.LanguageNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ServiceReference1.LanguageISOCodeResponse LanguageISOCode(ServiceReference1.LanguageISOCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.LanguageISOCodeResponse> LanguageISOCodeAsync(ServiceReference1.LanguageISOCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfContinentsByNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfContinentsByName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.ListOfContinentsByNameRequestBody Body;
        
        public ListOfContinentsByNameRequest()
        {
        }
        
        public ListOfContinentsByNameRequest(ServiceReference1.ListOfContinentsByNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListOfContinentsByNameRequestBody
    {
        
        public ListOfContinentsByNameRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfContinentsByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfContinentsByNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.ListOfContinentsByNameResponseBody Body;
        
        public ListOfContinentsByNameResponse()
        {
        }
        
        public ListOfContinentsByNameResponse(ServiceReference1.ListOfContinentsByNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class ListOfContinentsByNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.tContinent[] ListOfContinentsByNameResult;
        
        public ListOfContinentsByNameResponseBody()
        {
        }
        
        public ListOfContinentsByNameResponseBody(ServiceReference1.tContinent[] ListOfContinentsByNameResult)
        {
            this.ListOfContinentsByNameResult = ListOfContinentsByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfContinentsByCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfContinentsByCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.ListOfContinentsByCodeRequestBody Body;
        
        public ListOfContinentsByCodeRequest()
        {
        }
        
        public ListOfContinentsByCodeRequest(ServiceReference1.ListOfContinentsByCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListOfContinentsByCodeRequestBody
    {
        
        public ListOfContinentsByCodeRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfContinentsByCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfContinentsByCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.ListOfContinentsByCodeResponseBody Body;
        
        public ListOfContinentsByCodeResponse()
        {
        }
        
        public ListOfContinentsByCodeResponse(ServiceReference1.ListOfContinentsByCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class ListOfContinentsByCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.tContinent[] ListOfContinentsByCodeResult;
        
        public ListOfContinentsByCodeResponseBody()
        {
        }
        
        public ListOfContinentsByCodeResponseBody(ServiceReference1.tContinent[] ListOfContinentsByCodeResult)
        {
            this.ListOfContinentsByCodeResult = ListOfContinentsByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfCurrenciesByNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCurrenciesByName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.ListOfCurrenciesByNameRequestBody Body;
        
        public ListOfCurrenciesByNameRequest()
        {
        }
        
        public ListOfCurrenciesByNameRequest(ServiceReference1.ListOfCurrenciesByNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListOfCurrenciesByNameRequestBody
    {
        
        public ListOfCurrenciesByNameRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfCurrenciesByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCurrenciesByNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.ListOfCurrenciesByNameResponseBody Body;
        
        public ListOfCurrenciesByNameResponse()
        {
        }
        
        public ListOfCurrenciesByNameResponse(ServiceReference1.ListOfCurrenciesByNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class ListOfCurrenciesByNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.tCurrency[] ListOfCurrenciesByNameResult;
        
        public ListOfCurrenciesByNameResponseBody()
        {
        }
        
        public ListOfCurrenciesByNameResponseBody(ServiceReference1.tCurrency[] ListOfCurrenciesByNameResult)
        {
            this.ListOfCurrenciesByNameResult = ListOfCurrenciesByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfCurrenciesByCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCurrenciesByCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.ListOfCurrenciesByCodeRequestBody Body;
        
        public ListOfCurrenciesByCodeRequest()
        {
        }
        
        public ListOfCurrenciesByCodeRequest(ServiceReference1.ListOfCurrenciesByCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListOfCurrenciesByCodeRequestBody
    {
        
        public ListOfCurrenciesByCodeRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfCurrenciesByCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCurrenciesByCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.ListOfCurrenciesByCodeResponseBody Body;
        
        public ListOfCurrenciesByCodeResponse()
        {
        }
        
        public ListOfCurrenciesByCodeResponse(ServiceReference1.ListOfCurrenciesByCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class ListOfCurrenciesByCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.tCurrency[] ListOfCurrenciesByCodeResult;
        
        public ListOfCurrenciesByCodeResponseBody()
        {
        }
        
        public ListOfCurrenciesByCodeResponseBody(ServiceReference1.tCurrency[] ListOfCurrenciesByCodeResult)
        {
            this.ListOfCurrenciesByCodeResult = ListOfCurrenciesByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrencyNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrencyName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.CurrencyNameRequestBody Body;
        
        public CurrencyNameRequest()
        {
        }
        
        public CurrencyNameRequest(ServiceReference1.CurrencyNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CurrencyNameRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCurrencyISOCode;
        
        public CurrencyNameRequestBody()
        {
        }
        
        public CurrencyNameRequestBody(string sCurrencyISOCode)
        {
            this.sCurrencyISOCode = sCurrencyISOCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrencyNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrencyNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.CurrencyNameResponseBody Body;
        
        public CurrencyNameResponse()
        {
        }
        
        public CurrencyNameResponse(ServiceReference1.CurrencyNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CurrencyNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CurrencyNameResult;
        
        public CurrencyNameResponseBody()
        {
        }
        
        public CurrencyNameResponseBody(string CurrencyNameResult)
        {
            this.CurrencyNameResult = CurrencyNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfCountryNamesByCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCountryNamesByCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.ListOfCountryNamesByCodeRequestBody Body;
        
        public ListOfCountryNamesByCodeRequest()
        {
        }
        
        public ListOfCountryNamesByCodeRequest(ServiceReference1.ListOfCountryNamesByCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListOfCountryNamesByCodeRequestBody
    {
        
        public ListOfCountryNamesByCodeRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfCountryNamesByCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCountryNamesByCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.ListOfCountryNamesByCodeResponseBody Body;
        
        public ListOfCountryNamesByCodeResponse()
        {
        }
        
        public ListOfCountryNamesByCodeResponse(ServiceReference1.ListOfCountryNamesByCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class ListOfCountryNamesByCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.tCountryCodeAndName[] ListOfCountryNamesByCodeResult;
        
        public ListOfCountryNamesByCodeResponseBody()
        {
        }
        
        public ListOfCountryNamesByCodeResponseBody(ServiceReference1.tCountryCodeAndName[] ListOfCountryNamesByCodeResult)
        {
            this.ListOfCountryNamesByCodeResult = ListOfCountryNamesByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfCountryNamesByNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCountryNamesByName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.ListOfCountryNamesByNameRequestBody Body;
        
        public ListOfCountryNamesByNameRequest()
        {
        }
        
        public ListOfCountryNamesByNameRequest(ServiceReference1.ListOfCountryNamesByNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListOfCountryNamesByNameRequestBody
    {
        
        public ListOfCountryNamesByNameRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfCountryNamesByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCountryNamesByNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.ListOfCountryNamesByNameResponseBody Body;
        
        public ListOfCountryNamesByNameResponse()
        {
        }
        
        public ListOfCountryNamesByNameResponse(ServiceReference1.ListOfCountryNamesByNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class ListOfCountryNamesByNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.tCountryCodeAndName[] ListOfCountryNamesByNameResult;
        
        public ListOfCountryNamesByNameResponseBody()
        {
        }
        
        public ListOfCountryNamesByNameResponseBody(ServiceReference1.tCountryCodeAndName[] ListOfCountryNamesByNameResult)
        {
            this.ListOfCountryNamesByNameResult = ListOfCountryNamesByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfCountryNamesGroupedByContinentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCountryNamesGroupedByContinent", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.ListOfCountryNamesGroupedByContinentRequestBody Body;
        
        public ListOfCountryNamesGroupedByContinentRequest()
        {
        }
        
        public ListOfCountryNamesGroupedByContinentRequest(ServiceReference1.ListOfCountryNamesGroupedByContinentRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListOfCountryNamesGroupedByContinentRequestBody
    {
        
        public ListOfCountryNamesGroupedByContinentRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfCountryNamesGroupedByContinentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfCountryNamesGroupedByContinentResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.ListOfCountryNamesGroupedByContinentResponseBody Body;
        
        public ListOfCountryNamesGroupedByContinentResponse()
        {
        }
        
        public ListOfCountryNamesGroupedByContinentResponse(ServiceReference1.ListOfCountryNamesGroupedByContinentResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class ListOfCountryNamesGroupedByContinentResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.tCountryCodeAndNameGroupedByContinent[] ListOfCountryNamesGroupedByContinentResult;
        
        public ListOfCountryNamesGroupedByContinentResponseBody()
        {
        }
        
        public ListOfCountryNamesGroupedByContinentResponseBody(ServiceReference1.tCountryCodeAndNameGroupedByContinent[] ListOfCountryNamesGroupedByContinentResult)
        {
            this.ListOfCountryNamesGroupedByContinentResult = ListOfCountryNamesGroupedByContinentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountryNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.CountryNameRequestBody Body;
        
        public CountryNameRequest()
        {
        }
        
        public CountryNameRequest(ServiceReference1.CountryNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CountryNameRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCountryISOCode;
        
        public CountryNameRequestBody()
        {
        }
        
        public CountryNameRequestBody(string sCountryISOCode)
        {
            this.sCountryISOCode = sCountryISOCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountryNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.CountryNameResponseBody Body;
        
        public CountryNameResponse()
        {
        }
        
        public CountryNameResponse(ServiceReference1.CountryNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CountryNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CountryNameResult;
        
        public CountryNameResponseBody()
        {
        }
        
        public CountryNameResponseBody(string CountryNameResult)
        {
            this.CountryNameResult = CountryNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountryISOCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryISOCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.CountryISOCodeRequestBody Body;
        
        public CountryISOCodeRequest()
        {
        }
        
        public CountryISOCodeRequest(ServiceReference1.CountryISOCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CountryISOCodeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCountryName;
        
        public CountryISOCodeRequestBody()
        {
        }
        
        public CountryISOCodeRequestBody(string sCountryName)
        {
            this.sCountryName = sCountryName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountryISOCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryISOCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.CountryISOCodeResponseBody Body;
        
        public CountryISOCodeResponse()
        {
        }
        
        public CountryISOCodeResponse(ServiceReference1.CountryISOCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CountryISOCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CountryISOCodeResult;
        
        public CountryISOCodeResponseBody()
        {
        }
        
        public CountryISOCodeResponseBody(string CountryISOCodeResult)
        {
            this.CountryISOCodeResult = CountryISOCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CapitalCityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CapitalCity", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.CapitalCityRequestBody Body;
        
        public CapitalCityRequest()
        {
        }
        
        public CapitalCityRequest(ServiceReference1.CapitalCityRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CapitalCityRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCountryISOCode;
        
        public CapitalCityRequestBody()
        {
        }
        
        public CapitalCityRequestBody(string sCountryISOCode)
        {
            this.sCountryISOCode = sCountryISOCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CapitalCityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CapitalCityResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.CapitalCityResponseBody Body;
        
        public CapitalCityResponse()
        {
        }
        
        public CapitalCityResponse(ServiceReference1.CapitalCityResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CapitalCityResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CapitalCityResult;
        
        public CapitalCityResponseBody()
        {
        }
        
        public CapitalCityResponseBody(string CapitalCityResult)
        {
            this.CapitalCityResult = CapitalCityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountryCurrencyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryCurrency", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.CountryCurrencyRequestBody Body;
        
        public CountryCurrencyRequest()
        {
        }
        
        public CountryCurrencyRequest(ServiceReference1.CountryCurrencyRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CountryCurrencyRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCountryISOCode;
        
        public CountryCurrencyRequestBody()
        {
        }
        
        public CountryCurrencyRequestBody(string sCountryISOCode)
        {
            this.sCountryISOCode = sCountryISOCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountryCurrencyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryCurrencyResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.CountryCurrencyResponseBody Body;
        
        public CountryCurrencyResponse()
        {
        }
        
        public CountryCurrencyResponse(ServiceReference1.CountryCurrencyResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CountryCurrencyResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.tCurrency CountryCurrencyResult;
        
        public CountryCurrencyResponseBody()
        {
        }
        
        public CountryCurrencyResponseBody(ServiceReference1.tCurrency CountryCurrencyResult)
        {
            this.CountryCurrencyResult = CountryCurrencyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountryFlagRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryFlag", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.CountryFlagRequestBody Body;
        
        public CountryFlagRequest()
        {
        }
        
        public CountryFlagRequest(ServiceReference1.CountryFlagRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CountryFlagRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCountryISOCode;
        
        public CountryFlagRequestBody()
        {
        }
        
        public CountryFlagRequestBody(string sCountryISOCode)
        {
            this.sCountryISOCode = sCountryISOCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountryFlagResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryFlagResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.CountryFlagResponseBody Body;
        
        public CountryFlagResponse()
        {
        }
        
        public CountryFlagResponse(ServiceReference1.CountryFlagResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CountryFlagResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CountryFlagResult;
        
        public CountryFlagResponseBody()
        {
        }
        
        public CountryFlagResponseBody(string CountryFlagResult)
        {
            this.CountryFlagResult = CountryFlagResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountryIntPhoneCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryIntPhoneCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.CountryIntPhoneCodeRequestBody Body;
        
        public CountryIntPhoneCodeRequest()
        {
        }
        
        public CountryIntPhoneCodeRequest(ServiceReference1.CountryIntPhoneCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CountryIntPhoneCodeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCountryISOCode;
        
        public CountryIntPhoneCodeRequestBody()
        {
        }
        
        public CountryIntPhoneCodeRequestBody(string sCountryISOCode)
        {
            this.sCountryISOCode = sCountryISOCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountryIntPhoneCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountryIntPhoneCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.CountryIntPhoneCodeResponseBody Body;
        
        public CountryIntPhoneCodeResponse()
        {
        }
        
        public CountryIntPhoneCodeResponse(ServiceReference1.CountryIntPhoneCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CountryIntPhoneCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CountryIntPhoneCodeResult;
        
        public CountryIntPhoneCodeResponseBody()
        {
        }
        
        public CountryIntPhoneCodeResponseBody(string CountryIntPhoneCodeResult)
        {
            this.CountryIntPhoneCodeResult = CountryIntPhoneCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FullCountryInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FullCountryInfo", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.FullCountryInfoRequestBody Body;
        
        public FullCountryInfoRequest()
        {
        }
        
        public FullCountryInfoRequest(ServiceReference1.FullCountryInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class FullCountryInfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sCountryISOCode;
        
        public FullCountryInfoRequestBody()
        {
        }
        
        public FullCountryInfoRequestBody(string sCountryISOCode)
        {
            this.sCountryISOCode = sCountryISOCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FullCountryInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FullCountryInfoResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.FullCountryInfoResponseBody Body;
        
        public FullCountryInfoResponse()
        {
        }
        
        public FullCountryInfoResponse(ServiceReference1.FullCountryInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class FullCountryInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.tCountryInfo FullCountryInfoResult;
        
        public FullCountryInfoResponseBody()
        {
        }
        
        public FullCountryInfoResponseBody(ServiceReference1.tCountryInfo FullCountryInfoResult)
        {
            this.FullCountryInfoResult = FullCountryInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FullCountryInfoAllCountriesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FullCountryInfoAllCountries", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.FullCountryInfoAllCountriesRequestBody Body;
        
        public FullCountryInfoAllCountriesRequest()
        {
        }
        
        public FullCountryInfoAllCountriesRequest(ServiceReference1.FullCountryInfoAllCountriesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class FullCountryInfoAllCountriesRequestBody
    {
        
        public FullCountryInfoAllCountriesRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FullCountryInfoAllCountriesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FullCountryInfoAllCountriesResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.FullCountryInfoAllCountriesResponseBody Body;
        
        public FullCountryInfoAllCountriesResponse()
        {
        }
        
        public FullCountryInfoAllCountriesResponse(ServiceReference1.FullCountryInfoAllCountriesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class FullCountryInfoAllCountriesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.tCountryInfo[] FullCountryInfoAllCountriesResult;
        
        public FullCountryInfoAllCountriesResponseBody()
        {
        }
        
        public FullCountryInfoAllCountriesResponseBody(ServiceReference1.tCountryInfo[] FullCountryInfoAllCountriesResult)
        {
            this.FullCountryInfoAllCountriesResult = FullCountryInfoAllCountriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountriesUsingCurrencyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountriesUsingCurrency", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.CountriesUsingCurrencyRequestBody Body;
        
        public CountriesUsingCurrencyRequest()
        {
        }
        
        public CountriesUsingCurrencyRequest(ServiceReference1.CountriesUsingCurrencyRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CountriesUsingCurrencyRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sISOCurrencyCode;
        
        public CountriesUsingCurrencyRequestBody()
        {
        }
        
        public CountriesUsingCurrencyRequestBody(string sISOCurrencyCode)
        {
            this.sISOCurrencyCode = sISOCurrencyCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountriesUsingCurrencyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountriesUsingCurrencyResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.CountriesUsingCurrencyResponseBody Body;
        
        public CountriesUsingCurrencyResponse()
        {
        }
        
        public CountriesUsingCurrencyResponse(ServiceReference1.CountriesUsingCurrencyResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class CountriesUsingCurrencyResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.tCountryCodeAndName[] CountriesUsingCurrencyResult;
        
        public CountriesUsingCurrencyResponseBody()
        {
        }
        
        public CountriesUsingCurrencyResponseBody(ServiceReference1.tCountryCodeAndName[] CountriesUsingCurrencyResult)
        {
            this.CountriesUsingCurrencyResult = CountriesUsingCurrencyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfLanguagesByNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfLanguagesByName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.ListOfLanguagesByNameRequestBody Body;
        
        public ListOfLanguagesByNameRequest()
        {
        }
        
        public ListOfLanguagesByNameRequest(ServiceReference1.ListOfLanguagesByNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListOfLanguagesByNameRequestBody
    {
        
        public ListOfLanguagesByNameRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfLanguagesByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfLanguagesByNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.ListOfLanguagesByNameResponseBody Body;
        
        public ListOfLanguagesByNameResponse()
        {
        }
        
        public ListOfLanguagesByNameResponse(ServiceReference1.ListOfLanguagesByNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class ListOfLanguagesByNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.tLanguage[] ListOfLanguagesByNameResult;
        
        public ListOfLanguagesByNameResponseBody()
        {
        }
        
        public ListOfLanguagesByNameResponseBody(ServiceReference1.tLanguage[] ListOfLanguagesByNameResult)
        {
            this.ListOfLanguagesByNameResult = ListOfLanguagesByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfLanguagesByCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfLanguagesByCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.ListOfLanguagesByCodeRequestBody Body;
        
        public ListOfLanguagesByCodeRequest()
        {
        }
        
        public ListOfLanguagesByCodeRequest(ServiceReference1.ListOfLanguagesByCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListOfLanguagesByCodeRequestBody
    {
        
        public ListOfLanguagesByCodeRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListOfLanguagesByCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListOfLanguagesByCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.ListOfLanguagesByCodeResponseBody Body;
        
        public ListOfLanguagesByCodeResponse()
        {
        }
        
        public ListOfLanguagesByCodeResponse(ServiceReference1.ListOfLanguagesByCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class ListOfLanguagesByCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.tLanguage[] ListOfLanguagesByCodeResult;
        
        public ListOfLanguagesByCodeResponseBody()
        {
        }
        
        public ListOfLanguagesByCodeResponseBody(ServiceReference1.tLanguage[] ListOfLanguagesByCodeResult)
        {
            this.ListOfLanguagesByCodeResult = ListOfLanguagesByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LanguageNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LanguageName", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.LanguageNameRequestBody Body;
        
        public LanguageNameRequest()
        {
        }
        
        public LanguageNameRequest(ServiceReference1.LanguageNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class LanguageNameRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sISOCode;
        
        public LanguageNameRequestBody()
        {
        }
        
        public LanguageNameRequestBody(string sISOCode)
        {
            this.sISOCode = sISOCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LanguageNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LanguageNameResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.LanguageNameResponseBody Body;
        
        public LanguageNameResponse()
        {
        }
        
        public LanguageNameResponse(ServiceReference1.LanguageNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class LanguageNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LanguageNameResult;
        
        public LanguageNameResponseBody()
        {
        }
        
        public LanguageNameResponseBody(string LanguageNameResult)
        {
            this.LanguageNameResult = LanguageNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LanguageISOCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LanguageISOCode", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.LanguageISOCodeRequestBody Body;
        
        public LanguageISOCodeRequest()
        {
        }
        
        public LanguageISOCodeRequest(ServiceReference1.LanguageISOCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class LanguageISOCodeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sLanguageName;
        
        public LanguageISOCodeRequestBody()
        {
        }
        
        public LanguageISOCodeRequestBody(string sLanguageName)
        {
            this.sLanguageName = sLanguageName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LanguageISOCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LanguageISOCodeResponse", Namespace="http://www.oorsprong.org/websamples.countryinfo", Order=0)]
        public ServiceReference1.LanguageISOCodeResponseBody Body;
        
        public LanguageISOCodeResponse()
        {
        }
        
        public LanguageISOCodeResponse(ServiceReference1.LanguageISOCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.oorsprong.org/websamples.countryinfo")]
    public partial class LanguageISOCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LanguageISOCodeResult;
        
        public LanguageISOCodeResponseBody()
        {
        }
        
        public LanguageISOCodeResponseBody(string LanguageISOCodeResult)
        {
            this.LanguageISOCodeResult = LanguageISOCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface CountryInfoServiceSoapTypeChannel : ServiceReference1.CountryInfoServiceSoapType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class CountryInfoServiceSoapTypeClient : System.ServiceModel.ClientBase<ServiceReference1.CountryInfoServiceSoapType>, ServiceReference1.CountryInfoServiceSoapType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CountryInfoServiceSoapTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(CountryInfoServiceSoapTypeClient.GetBindingForEndpoint(endpointConfiguration), CountryInfoServiceSoapTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CountryInfoServiceSoapTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CountryInfoServiceSoapTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CountryInfoServiceSoapTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CountryInfoServiceSoapTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CountryInfoServiceSoapTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReference1.ListOfContinentsByNameResponse ListOfContinentsByName(ServiceReference1.ListOfContinentsByNameRequest request)
        {
            return base.Channel.ListOfContinentsByName(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ListOfContinentsByNameResponse> ListOfContinentsByNameAsync(ServiceReference1.ListOfContinentsByNameRequest request)
        {
            return base.Channel.ListOfContinentsByNameAsync(request);
        }
        
        public ServiceReference1.ListOfContinentsByCodeResponse ListOfContinentsByCode(ServiceReference1.ListOfContinentsByCodeRequest request)
        {
            return base.Channel.ListOfContinentsByCode(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ListOfContinentsByCodeResponse> ListOfContinentsByCodeAsync(ServiceReference1.ListOfContinentsByCodeRequest request)
        {
            return base.Channel.ListOfContinentsByCodeAsync(request);
        }
        
        public ServiceReference1.ListOfCurrenciesByNameResponse ListOfCurrenciesByName(ServiceReference1.ListOfCurrenciesByNameRequest request)
        {
            return base.Channel.ListOfCurrenciesByName(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ListOfCurrenciesByNameResponse> ListOfCurrenciesByNameAsync(ServiceReference1.ListOfCurrenciesByNameRequest request)
        {
            return base.Channel.ListOfCurrenciesByNameAsync(request);
        }
        
        public ServiceReference1.ListOfCurrenciesByCodeResponse ListOfCurrenciesByCode(ServiceReference1.ListOfCurrenciesByCodeRequest request)
        {
            return base.Channel.ListOfCurrenciesByCode(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ListOfCurrenciesByCodeResponse> ListOfCurrenciesByCodeAsync(ServiceReference1.ListOfCurrenciesByCodeRequest request)
        {
            return base.Channel.ListOfCurrenciesByCodeAsync(request);
        }
        
        public ServiceReference1.CurrencyNameResponse CurrencyName(ServiceReference1.CurrencyNameRequest request)
        {
            return base.Channel.CurrencyName(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CurrencyNameResponse> CurrencyNameAsync(ServiceReference1.CurrencyNameRequest request)
        {
            return base.Channel.CurrencyNameAsync(request);
        }
        
        public ServiceReference1.ListOfCountryNamesByCodeResponse ListOfCountryNamesByCode(ServiceReference1.ListOfCountryNamesByCodeRequest request)
        {
            return base.Channel.ListOfCountryNamesByCode(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ListOfCountryNamesByCodeResponse> ListOfCountryNamesByCodeAsync(ServiceReference1.ListOfCountryNamesByCodeRequest request)
        {
            return base.Channel.ListOfCountryNamesByCodeAsync(request);
        }
        
        public ServiceReference1.ListOfCountryNamesByNameResponse ListOfCountryNamesByName(ServiceReference1.ListOfCountryNamesByNameRequest request)
        {
            return base.Channel.ListOfCountryNamesByName(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ListOfCountryNamesByNameResponse> ListOfCountryNamesByNameAsync(ServiceReference1.ListOfCountryNamesByNameRequest request)
        {
            return base.Channel.ListOfCountryNamesByNameAsync(request);
        }
        
        public ServiceReference1.ListOfCountryNamesGroupedByContinentResponse ListOfCountryNamesGroupedByContinent(ServiceReference1.ListOfCountryNamesGroupedByContinentRequest request)
        {
            return base.Channel.ListOfCountryNamesGroupedByContinent(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ListOfCountryNamesGroupedByContinentResponse> ListOfCountryNamesGroupedByContinentAsync(ServiceReference1.ListOfCountryNamesGroupedByContinentRequest request)
        {
            return base.Channel.ListOfCountryNamesGroupedByContinentAsync(request);
        }
        
        public ServiceReference1.CountryNameResponse CountryName(ServiceReference1.CountryNameRequest request)
        {
            return base.Channel.CountryName(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CountryNameResponse> CountryNameAsync(ServiceReference1.CountryNameRequest request)
        {
            return base.Channel.CountryNameAsync(request);
        }
        
        public ServiceReference1.CountryISOCodeResponse CountryISOCode(ServiceReference1.CountryISOCodeRequest request)
        {
            return base.Channel.CountryISOCode(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CountryISOCodeResponse> CountryISOCodeAsync(ServiceReference1.CountryISOCodeRequest request)
        {
            return base.Channel.CountryISOCodeAsync(request);
        }
        
        public ServiceReference1.CapitalCityResponse CapitalCity(ServiceReference1.CapitalCityRequest request)
        {
            return base.Channel.CapitalCity(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CapitalCityResponse> CapitalCityAsync(ServiceReference1.CapitalCityRequest request)
        {
            return base.Channel.CapitalCityAsync(request);
        }
        
        public ServiceReference1.CountryCurrencyResponse CountryCurrency(ServiceReference1.CountryCurrencyRequest request)
        {
            return base.Channel.CountryCurrency(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CountryCurrencyResponse> CountryCurrencyAsync(ServiceReference1.CountryCurrencyRequest request)
        {
            return base.Channel.CountryCurrencyAsync(request);
        }
        
        public ServiceReference1.CountryFlagResponse CountryFlag(ServiceReference1.CountryFlagRequest request)
        {
            return base.Channel.CountryFlag(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CountryFlagResponse> CountryFlagAsync(ServiceReference1.CountryFlagRequest request)
        {
            return base.Channel.CountryFlagAsync(request);
        }
        
        public ServiceReference1.CountryIntPhoneCodeResponse CountryIntPhoneCode(ServiceReference1.CountryIntPhoneCodeRequest request)
        {
            return base.Channel.CountryIntPhoneCode(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CountryIntPhoneCodeResponse> CountryIntPhoneCodeAsync(ServiceReference1.CountryIntPhoneCodeRequest request)
        {
            return base.Channel.CountryIntPhoneCodeAsync(request);
        }
        
        public ServiceReference1.FullCountryInfoResponse FullCountryInfo(ServiceReference1.FullCountryInfoRequest request)
        {
            return base.Channel.FullCountryInfo(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.FullCountryInfoResponse> FullCountryInfoAsync(ServiceReference1.FullCountryInfoRequest request)
        {
            return base.Channel.FullCountryInfoAsync(request);
        }
        
        public ServiceReference1.FullCountryInfoAllCountriesResponse FullCountryInfoAllCountries(ServiceReference1.FullCountryInfoAllCountriesRequest request)
        {
            return base.Channel.FullCountryInfoAllCountries(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.FullCountryInfoAllCountriesResponse> FullCountryInfoAllCountriesAsync(ServiceReference1.FullCountryInfoAllCountriesRequest request)
        {
            return base.Channel.FullCountryInfoAllCountriesAsync(request);
        }
        
        public ServiceReference1.CountriesUsingCurrencyResponse CountriesUsingCurrency(ServiceReference1.CountriesUsingCurrencyRequest request)
        {
            return base.Channel.CountriesUsingCurrency(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CountriesUsingCurrencyResponse> CountriesUsingCurrencyAsync(ServiceReference1.CountriesUsingCurrencyRequest request)
        {
            return base.Channel.CountriesUsingCurrencyAsync(request);
        }
        
        public ServiceReference1.ListOfLanguagesByNameResponse ListOfLanguagesByName(ServiceReference1.ListOfLanguagesByNameRequest request)
        {
            return base.Channel.ListOfLanguagesByName(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ListOfLanguagesByNameResponse> ListOfLanguagesByNameAsync(ServiceReference1.ListOfLanguagesByNameRequest request)
        {
            return base.Channel.ListOfLanguagesByNameAsync(request);
        }
        
        public ServiceReference1.ListOfLanguagesByCodeResponse ListOfLanguagesByCode(ServiceReference1.ListOfLanguagesByCodeRequest request)
        {
            return base.Channel.ListOfLanguagesByCode(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ListOfLanguagesByCodeResponse> ListOfLanguagesByCodeAsync(ServiceReference1.ListOfLanguagesByCodeRequest request)
        {
            return base.Channel.ListOfLanguagesByCodeAsync(request);
        }
        
        public ServiceReference1.LanguageNameResponse LanguageName(ServiceReference1.LanguageNameRequest request)
        {
            return base.Channel.LanguageName(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.LanguageNameResponse> LanguageNameAsync(ServiceReference1.LanguageNameRequest request)
        {
            return base.Channel.LanguageNameAsync(request);
        }
        
        public ServiceReference1.LanguageISOCodeResponse LanguageISOCode(ServiceReference1.LanguageISOCodeRequest request)
        {
            return base.Channel.LanguageISOCode(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.LanguageISOCodeResponse> LanguageISOCodeAsync(ServiceReference1.LanguageISOCodeRequest request)
        {
            return base.Channel.LanguageISOCodeAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CountryInfoServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CountryInfoServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CountryInfoServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso");
            }
            if ((endpointConfiguration == EndpointConfiguration.CountryInfoServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CountryInfoServiceSoap,
            
            CountryInfoServiceSoap12,
        }
    }
}
